### ISSUE TITLE
Is this Real ???

### ISSUE THREAD

**Issue by oxaendri** [haephrati/MT5-DLL-C#1]
Hello Sir.

Can this library be used for communication between a c++ program and a metatrader server without need for terminal or gui interfaces ? 

thanks !!

**Comment by haephrati** [comment]
> Hello Sir.
> 
> Can this library be used for communication between a c++ program and a metatrader server without need for terminal or gui interfaces ?
> 
> thanks !!

It sure can but that would need more work which I am happy to provide. (it won't be free, though).

**Comment by haephrati** [comment]
> you know what that means right there are people selling these sources for 1k - 10k

I am selling for more and the most important part is the customisation.
